### ISSUE TITLE
"Ship it" cannot be published

### ISSUE THREAD

**Issue by uekemp** [ritesh-kapoor/review-board-idea-plugin#20] opened 2016-01-04 09:30 UTC
When pressing the "ship it" button for a review (without adding comments), the review is shipped, but not yet published (which is OK). But currently there seems to be no way of publishing the review as the "Publish Review" button is disabled. Refreshing also doens't work, need to open the review in the browser to publish.

Plugin v0.1.2
AS 2.0 Preview 4

**Comment by meran** [comment] 2016-02-23 12:42
after a lot investigating I found that the web API does not support the changing of ship it status.

from the documentation:
The only supported update to a review request’s resource is to change the status, the associated server-side, change number, or to update information from the existing change number.

**Comment by meran** [comment] 2016-03-02 08:53
my last reply was a mistake.
it is a bug in the plugin code.
in the file Http.Request.Builder.java
function createReviewApi
need to add all the parameters and not just ship_it true:

requestBuilder.field("ship_it", shipIt);
            requestBuilder.field("api_format", "json");
            requestBuilder.field("body_top", "you are allowed to ship it!");
            requestBuilder.field("body_top_text_type", "plain");
            requestBuilder.field("body_bottom", "");
            requestBuilder.field("body_bottom_text_type", "plain");
            requestBuilder.field("public", "1");

this solved the issue

**Comment by ritesh-kapoor** [comment] 2016-03-03 18:45
Could you please confirm if the issue is fixed in new build (https://github.com/ritesh-kapoor/review-board-idea-plugin/releases/tag/v0.1.3-beta.1)

**Comment by uekemp** [comment] 2016-03-04 07:51
Yes, I can confirm the ship it button works now (0.1.3-beta) as expected, thank you!

**Comment by ritesh-kapoor** [comment] 2016-03-08 07:34
Thanks @uekemp

**Closed as completed** 2016-03-08 07:34 UTC
