### ISSUE TITLE
Comments cannot be marked as issues

### ISSUE THREAD

**Issue by uekemp** [ritesh-kapoor/review-board-idea-plugin#21] opened 2016-01-04 14:51 UTC
Feature request: when adding a comment via the diff viewer, it is not possible to open an issue for the comment (like in review board). This way it is much more difficult to see which reuests have been reviewed in the dashboard.

**Comment by ritesh-kapoor** [comment] 2016-03-03 18:46
Could you please confirm if the issue is fixed in new build (https://github.com/ritesh-kapoor/review-board-idea-plugin/releases/tag/v0.1.3-beta.1)

**Comment by uekemp** [comment] 2016-03-04 07:49
Yes great, it is working now with the 0.1.3-beta version. Thanks!

**Comment by ritesh-kapoor** [comment] 2016-03-08 07:36
Thanks @uekemp

**Closed as completed by ritesh-kapoor** 2016-03-08 07:36 UTC
