### ISSUE TITLE
"rbt" not found when using RBTools option checked

### ISSUE THREAD

**Issue by waqarkhan88** [ritesh-kapoor/review-board-idea-plugin#26] opened 2016-01-22 17:07 UTC
ReviewBoard: Cannot run program "rbt" (in directory <ProjectPath>): CreateProcess error=2, The system cannot find the file specified

I de-compiled RbToolsDiffProvider class and found that the way you are invoking rbt.cmd environment variable PATH will not be available to it. It would need absolute path to rbt.cmd file. I verified by running rbt command using command prompt, its working fine and the path is added in PATH system variable.

I am using Intellij Idea 14 on windows 10. I am using CVS that's why i have no option but to use RBT tool option.

**Comment by rogerdubbs** [comment] 2016-02-16 22:53
Same issue but on a mac.  The terminal window finds rbt just fine at /usr/local/bin/rbt, but the plugin can't find it.

**Comment by ritesh-kapoor** [comment] 2016-03-03 18:48
Could you please confirm if the issue is fixed in new build (https://github.com/ritesh-kapoor/review-board-idea-plugin/releases/tag/v0.1.3-beta.1)

**Comment by ritesh-kapoor** [comment] 2016-03-03 18:48
You can now add explict path in settings

**Comment by waqarkhan88** [comment] 2016-03-07 11:09
After installing this version i am getting following error, I am using IntelliJ IDEA 15 Build# IU-143.381:

4:05:57 PM PluginException: com/ritesh/idea/plugin/ui/toolswindow/ReviewBoardToolsWindow : Unsupported major.minor version 51.0 [Plugin: com.ritesh.intellij.plugin.reviewboard]
4:07:01 PM PluginException: cannot create class "com.ritesh.idea.plugin.ui.action.ShowReviewBoard" [Plugin: com.ritesh.intellij.plugin.reviewboard]

**Comment by waqarkhan88** [comment] 2016-03-07 13:45
Sorry my mistake, it was issue of JDK. Now its working fine but i have noticed another issue which is if i select a file in version control tab and post review it sends all modified files for review instead of only selected files. Can you please look into it.

**Closed as completed** 2016-03-07 13:52 UTC

**Comment by aadilfarooqui** [comment] 2016-08-11 09:13
@waqarkhan88 Thanks for the words 'absolute path' for rbtools as I was also getting the error 

> "ReviewBoard: Cannot run program "rbt" (in directory ): CreateProcess error=2, The system cannot find the file specified"

 when working on **Intellij 16**. Now it works fine with it.
